spring.application.name=courseapp

# MySQL konfiguracija
spring.datasource.url=jdbc:mysql://localhost:3306/course_app_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=your database username
spring.datasource.password=your database pass 

# JPA konfiguracija
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Port aplikacije
server.port=8080

# JWT konfiguracija
jwt.secret=passwordAtLeast32CharactersLong
jwt.expiration=86400000 
# 24h

logging.level.org.springframework.security=DEBUG